### PR TITLE
fix: Fix nullable primitive responses

### LINKED ISSUE #85: Error converting nullable primitives
Converting nullable primitive types seems to result in an exception. I'm very new to Kiota, but try to describe my observations as good as possible.

The problematic part in the openapi.json:

```json
"/api/Developer/version": {
  "get": {
    "tags": [
      "Developer"
    ],
    "summary": "Returns the project version.",
    "responses": {
      "200": {
        "description": "OK",
        "content": {
          "text/plain": {
            "schema": {
              "type": "string"
            }
          },
          "application/json": {
            "schema": {
              "type": "string"
            }
          },
          "text/json": {
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
},
```

This generates this request builder:

```dart
Future<String?> getAsync([
  void Function(RequestConfiguration<DefaultQueryParameters>)?
  requestConfiguration,
]) async {
  var requestInfo = toGetRequestInformation(requestConfiguration);
  return await requestAdapter.sendPrimitive<String?>(requestInfo, {});
}
```

As `sendPrimitive` only accepts non-nullable types an `ArgumentError` is thrown.

I can handle the issue by removing the ? in the generated client, but would therefore have to do it after each regeneration.

### PR DESCRIPTION
**Pull request by ricardoboss**
This fixes #85.

Thanks to @mateusfccp for helping me figure this out!

---

I added special subtype checks for `DateOnly` and `TimeOnly` because those two are interfaces that might have third-party implementations.

### CODE REVIEW

File: packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart [hunk 1]
```diff
@@ -254,29 +260,28 @@ class HttpClientRequestAdapter implements RequestAdapter {
...
+      return rootNode.getBoolValue() as ModelType;
+    } else if (_isExactly<ModelType, int>() || _isExactly<ModelType, int?>()) {
+      return rootNode.getIntValue() as ModelType;
+    } else if (_isExactly<ModelType, double>() || _isExactly<ModelType, double?>()) {
+      return rootNode.getDoubleValue() as ModelType;
+    } else if (_isExactly<ModelType, String>() || _isExactly<ModelType, String?>()) {
+      return rootNode.getStringValue() as ModelType;
+    } else if (_isExactly<ModelType, DateTime>() || _isExactly<ModelType, DateTime?>()) {
+      return rootNode.getDateTimeValue() as ModelType;
+    } else if (_isExactly<ModelType, DateOnly>() || _isExactly<ModelType, DateOnly?>() || _isSubtype<ModelType, DateOnly?>()) {
```
Comment (mateusfccp) [inline packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:273]: I think this is equivalent to:

```suggestion
    } else if (_isSubtype<ModelType, DateOnly?>()) {
```

Comment (mateusfccp) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:273]: The same for `TimeOnly`

Comment (ricardoboss) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart]: Thank you!

File: packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart [hunk 2]
```diff
@@ -254,29 +260,33 @@ class HttpClientRequestAdapter implements RequestAdapter {
...
-        return rootNode.getTimeOnlyValue() as ModelType;
-      case const (Duration):
-        return rootNode.getDurationValue() as ModelType;
-      case const (UuidValue):
-        return rootNode.getGuidValue() as ModelType;
-      default:
-        throw ArgumentError(
-          'The type $ModelType is not supported for primitive deserialization',
-        );
+    if (_isExactly<ModelType, bool>() || _isExactly<ModelType, bool?>()) {
```
Comment (mateusfccp) [inline packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: Not anything critical, but considering that all uses of `_isExactly` use it for non-nullable and nullable, we could change it to

```dart
  @pragma('vm:prefer-inline')
  bool _isExactlyOrNullable<T, U>() => T == U || T == U?;
```

Comment (ricardoboss) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: Wait so Dart doesn't support nullable type literals but it does support nullable generic type literals?

---

Checked, doesn't work. Same issue as with other nullable literal types.

Comment (mateusfccp) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: Oh, that makes sense lol

Comment (mateusfccp) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: We could still abstract in a different way, if you feel it is worthy, but feel free to close it and do as you prefer.

Comment (ricardoboss) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: I mean, after inlining, it both results in the same code anyways 🙃

Comment (ricardoboss) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: > We could still abstract in a different way

You have another idea?

Comment (mateusfccp) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: > I mean, after inlining, it both results in the same code anyways 🙃

Yes, it's just that I feel like it's a little hard to read.

> You have another idea?

If you feel like it's worthy, we can workaround the workaround with:

```dart
Type typeOf<T>() => T;

bool _isExactly<T, U>() => T == U || T == typeOf<U?>();
```

But it's just a stylistic preference.

Comment (mateusfccp) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: Interestingly, there's a issue proposing to drop type literals completely in favor of a `typeOf` function.

https://github.com/dart-lang/language/issues/2393

Comment (ricardoboss) [reply packages/microsoft_kiota_http/lib/src/http_client_request_adapter.dart:263]: That's a good idea! The issue you linked also sounds interesting

**Review by baywet — APPROVED** [review]
Thanks for the contribution!

I'll let @mateusfccp give another review before I merged this

**Comment by mateusfccp** [comment]
@baywet I'm not fully aware of the business rules behind this, but code-wise LGTM.
